### PR TITLE
feat:scarb scripts

### PR DESCRIPTION
**Pull request by enitrat**
Use scarb scripts instead of Makefile
This is _not mergeable_ as CI fails until scarb is updated with alpha.7 (soon)
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by abdelhamidbakhta** [comment]
Thanks for this contribution. Can you put it as draft PR until Scarb is ready ?

**Comment by Eikix** [comment]
> Thanks for this contribution. Can you put it as draft PR until Scarb is ready ?

Do we know the ETA on Scarb readiness?

**Comment by enitrat** [comment]
> > Thanks for this contribution. Can you put it as draft PR until Scarb is ready ?
> 
> Do we know the ETA on Scarb readiness?

I think they're waiting for alpha.7 and idk when SW will release it

**Comment by enitrat** [comment]
will finish this after next pr

**Comment by enitrat** [comment]
Closing as it doesn't offer any benefit yet.

**Pull request closed without merging**
